### ISSUE TITLE
vue-meta duplicating tags on SSR hydration

### ISSUE THREAD

**Issue by jnields** [nuxt/vue-meta#404]
Specifically it looks like this line:

https://github.com/nuxt/vue-meta/blob/f1511ac566588adef7558dd02219688d860d6d35/src/shared/mixin.js#L82

checks to see if the app is performing SSR hydration

However, by the time it gets here, Vue's already removed the `data-server-rendered` attribute from the root element, and so it recreates all the tags.

I haven't looked into this in-depth, but could you just set all the tags to include `data-vue-meta="1"` during SSR instead of `data-vue-meta="ssr"` and skip this check?

Using vue@2.6.10

**Comment by pimlie** [comment]
Hydration occurs when the app is mounted, the check for `data-server-rendered` is in a synchronous `beforeMount` hook. So I am not sure how the `data-server-rendered` attribute can be removed before the `beforeMount` hook runs?

I guess this issue was instigated because you experienced duplicate tags? Please create a reproduction when possible, maybe the cause is somewhere else?

**Comment by jnields** [comment]
https://github.com/jnields/vue-meta-repro

**Comment by pimlie** [comment]
Thanks, can confirm this issue exists.

Its caused because the component which sets metaInfo is lazy loaded due to only calling it in the render function of your root component. Because of this, Vue only knows about the `A` component when it starts rendering the Root component on mounting the App/Root component. And when the beforeMount hook of VueMeta then triggers indeed the $root is already mounted and the data-server-rendered attributes have been removed.

If you would change the Root component to the following then you will only have one tag.

```js
export default Vue.extend({
  components: { A },
  name: 'Root',
  template: '<A />'
});
```
Will have a look at changing this behaviour and support your use-case. In the mean time please have a look if you can incorporate this workaround :)

**Comment by pimlie** [comment]
I have made the appId used on ssr configurable. So you can manually set `ssrAppId: 1` as option to VueMeta. Its still not an ideal solution but at least there is a workaround.

Will update when the workaround is releasd

**Comment by pimlie** [comment]
v2.1 has been released with the ability to configure the ssrAppId

Also check: https://vue-meta.nuxtjs.org/guide/caveats.html#duplicated-tags-after-hydration-with-ssr

**Comment by milewski** [comment]
Im having this problem now with script .. for instance:

![image](https://user-images.githubusercontent.com/2874967/82141097-2f8bd200-9866-11ea-8527-5f40f9a2e290.png)

The pre-rendered HTML only includes the bottom ones.. but once the page one the ones on the header gets injected 

I have set `ssrAppId` to 1 as seen on the screenshot above.. and the HTML tag initially has a `data-vue-meta-server-rendered` and then it gets removed

**Comment by pimlie** [comment]
Thanks, this will probably be fixed by #563. But Im waiting for some reviews before merging because the fix contains an assumption (see the code comment) and those are always tricky

**Comment by milewski** [comment]
I just tried installing that PR and the issue still remains.. my setup is the following:

```js
//My Route:

routes.push({
    path: '/',
    name: 'home',
    component: () => import('./pages/Home.vue') // <-- async
})

//My Home.vue

export default {
    metaInfo() {
        return [
            {
                vmid: md5(JSON.stringify('...')),
                type: 'application/ld+json',
                json: '...'
            },

            {
                vmid: md5(JSON.stringify('...')),
                type: 'application/ld+json',
                json: '...'
            }
        ]

    }
}
```

**Comment by pimlie** [comment]
@milewski Thanks, could you please make a full reproduction on jsfiddle or codesandbox I can check out?

**Comment by milewski** [comment]
Hi @pimlie https://github.com/milewski/vue-meta-bug , run `npm run build && npm run spa`
